# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chenziyan/ppfim_tfhe/ppfim_tfhe

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chenziyan/ppfim_tfhe/ppfim_tfhe

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chenziyan/ppfim_tfhe/ppfim_tfhe/CMakeFiles /home/chenziyan/ppfim_tfhe/ppfim_tfhe/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chenziyan/ppfim_tfhe/ppfim_tfhe/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_miner

# Build rule for target.
test_miner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_miner
.PHONY : test_miner

# fast build rule for target.
test_miner/fast:
	$(MAKE) -f CMakeFiles/test_miner.dir/build.make CMakeFiles/test_miner.dir/build
.PHONY : test_miner/fast

#=============================================================================
# Target rules for targets named test_user

# Build rule for target.
test_user: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_user
.PHONY : test_user

# fast build rule for target.
test_user/fast:
	$(MAKE) -f CMakeFiles/test_user.dir/build.make CMakeFiles/test_user.dir/build
.PHONY : test_user/fast

#=============================================================================
# Target rules for targets named test_cloud

# Build rule for target.
test_cloud: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_cloud
.PHONY : test_cloud

# fast build rule for target.
test_cloud/fast:
	$(MAKE) -f CMakeFiles/test_cloud.dir/build.make CMakeFiles/test_cloud.dir/build
.PHONY : test_cloud/fast

#=============================================================================
# Target rules for targets named test_performance

# Build rule for target.
test_performance: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_performance
.PHONY : test_performance

# fast build rule for target.
test_performance/fast:
	$(MAKE) -f CMakeFiles/test_performance.dir/build.make CMakeFiles/test_performance.dir/build
.PHONY : test_performance/fast

src/cloud.o: src/cloud.cpp.o

.PHONY : src/cloud.o

# target to build an object file
src/cloud.cpp.o:
	$(MAKE) -f CMakeFiles/test_cloud.dir/build.make CMakeFiles/test_cloud.dir/src/cloud.cpp.o
	$(MAKE) -f CMakeFiles/test_performance.dir/build.make CMakeFiles/test_performance.dir/src/cloud.cpp.o
.PHONY : src/cloud.cpp.o

src/cloud.i: src/cloud.cpp.i

.PHONY : src/cloud.i

# target to preprocess a source file
src/cloud.cpp.i:
	$(MAKE) -f CMakeFiles/test_cloud.dir/build.make CMakeFiles/test_cloud.dir/src/cloud.cpp.i
	$(MAKE) -f CMakeFiles/test_performance.dir/build.make CMakeFiles/test_performance.dir/src/cloud.cpp.i
.PHONY : src/cloud.cpp.i

src/cloud.s: src/cloud.cpp.s

.PHONY : src/cloud.s

# target to generate assembly for a file
src/cloud.cpp.s:
	$(MAKE) -f CMakeFiles/test_cloud.dir/build.make CMakeFiles/test_cloud.dir/src/cloud.cpp.s
	$(MAKE) -f CMakeFiles/test_performance.dir/build.make CMakeFiles/test_performance.dir/src/cloud.cpp.s
.PHONY : src/cloud.cpp.s

src/miner.o: src/miner.cpp.o

.PHONY : src/miner.o

# target to build an object file
src/miner.cpp.o:
	$(MAKE) -f CMakeFiles/test_miner.dir/build.make CMakeFiles/test_miner.dir/src/miner.cpp.o
	$(MAKE) -f CMakeFiles/test_performance.dir/build.make CMakeFiles/test_performance.dir/src/miner.cpp.o
.PHONY : src/miner.cpp.o

src/miner.i: src/miner.cpp.i

.PHONY : src/miner.i

# target to preprocess a source file
src/miner.cpp.i:
	$(MAKE) -f CMakeFiles/test_miner.dir/build.make CMakeFiles/test_miner.dir/src/miner.cpp.i
	$(MAKE) -f CMakeFiles/test_performance.dir/build.make CMakeFiles/test_performance.dir/src/miner.cpp.i
.PHONY : src/miner.cpp.i

src/miner.s: src/miner.cpp.s

.PHONY : src/miner.s

# target to generate assembly for a file
src/miner.cpp.s:
	$(MAKE) -f CMakeFiles/test_miner.dir/build.make CMakeFiles/test_miner.dir/src/miner.cpp.s
	$(MAKE) -f CMakeFiles/test_performance.dir/build.make CMakeFiles/test_performance.dir/src/miner.cpp.s
.PHONY : src/miner.cpp.s

src/test_cloud.o: src/test_cloud.cpp.o

.PHONY : src/test_cloud.o

# target to build an object file
src/test_cloud.cpp.o:
	$(MAKE) -f CMakeFiles/test_cloud.dir/build.make CMakeFiles/test_cloud.dir/src/test_cloud.cpp.o
.PHONY : src/test_cloud.cpp.o

src/test_cloud.i: src/test_cloud.cpp.i

.PHONY : src/test_cloud.i

# target to preprocess a source file
src/test_cloud.cpp.i:
	$(MAKE) -f CMakeFiles/test_cloud.dir/build.make CMakeFiles/test_cloud.dir/src/test_cloud.cpp.i
.PHONY : src/test_cloud.cpp.i

src/test_cloud.s: src/test_cloud.cpp.s

.PHONY : src/test_cloud.s

# target to generate assembly for a file
src/test_cloud.cpp.s:
	$(MAKE) -f CMakeFiles/test_cloud.dir/build.make CMakeFiles/test_cloud.dir/src/test_cloud.cpp.s
.PHONY : src/test_cloud.cpp.s

src/test_miner.o: src/test_miner.cpp.o

.PHONY : src/test_miner.o

# target to build an object file
src/test_miner.cpp.o:
	$(MAKE) -f CMakeFiles/test_miner.dir/build.make CMakeFiles/test_miner.dir/src/test_miner.cpp.o
.PHONY : src/test_miner.cpp.o

src/test_miner.i: src/test_miner.cpp.i

.PHONY : src/test_miner.i

# target to preprocess a source file
src/test_miner.cpp.i:
	$(MAKE) -f CMakeFiles/test_miner.dir/build.make CMakeFiles/test_miner.dir/src/test_miner.cpp.i
.PHONY : src/test_miner.cpp.i

src/test_miner.s: src/test_miner.cpp.s

.PHONY : src/test_miner.s

# target to generate assembly for a file
src/test_miner.cpp.s:
	$(MAKE) -f CMakeFiles/test_miner.dir/build.make CMakeFiles/test_miner.dir/src/test_miner.cpp.s
.PHONY : src/test_miner.cpp.s

src/test_performance.o: src/test_performance.cpp.o

.PHONY : src/test_performance.o

# target to build an object file
src/test_performance.cpp.o:
	$(MAKE) -f CMakeFiles/test_performance.dir/build.make CMakeFiles/test_performance.dir/src/test_performance.cpp.o
.PHONY : src/test_performance.cpp.o

src/test_performance.i: src/test_performance.cpp.i

.PHONY : src/test_performance.i

# target to preprocess a source file
src/test_performance.cpp.i:
	$(MAKE) -f CMakeFiles/test_performance.dir/build.make CMakeFiles/test_performance.dir/src/test_performance.cpp.i
.PHONY : src/test_performance.cpp.i

src/test_performance.s: src/test_performance.cpp.s

.PHONY : src/test_performance.s

# target to generate assembly for a file
src/test_performance.cpp.s:
	$(MAKE) -f CMakeFiles/test_performance.dir/build.make CMakeFiles/test_performance.dir/src/test_performance.cpp.s
.PHONY : src/test_performance.cpp.s

src/test_user.o: src/test_user.cpp.o

.PHONY : src/test_user.o

# target to build an object file
src/test_user.cpp.o:
	$(MAKE) -f CMakeFiles/test_user.dir/build.make CMakeFiles/test_user.dir/src/test_user.cpp.o
.PHONY : src/test_user.cpp.o

src/test_user.i: src/test_user.cpp.i

.PHONY : src/test_user.i

# target to preprocess a source file
src/test_user.cpp.i:
	$(MAKE) -f CMakeFiles/test_user.dir/build.make CMakeFiles/test_user.dir/src/test_user.cpp.i
.PHONY : src/test_user.cpp.i

src/test_user.s: src/test_user.cpp.s

.PHONY : src/test_user.s

# target to generate assembly for a file
src/test_user.cpp.s:
	$(MAKE) -f CMakeFiles/test_user.dir/build.make CMakeFiles/test_user.dir/src/test_user.cpp.s
.PHONY : src/test_user.cpp.s

src/user.o: src/user.cpp.o

.PHONY : src/user.o

# target to build an object file
src/user.cpp.o:
	$(MAKE) -f CMakeFiles/test_user.dir/build.make CMakeFiles/test_user.dir/src/user.cpp.o
	$(MAKE) -f CMakeFiles/test_cloud.dir/build.make CMakeFiles/test_cloud.dir/src/user.cpp.o
	$(MAKE) -f CMakeFiles/test_performance.dir/build.make CMakeFiles/test_performance.dir/src/user.cpp.o
.PHONY : src/user.cpp.o

src/user.i: src/user.cpp.i

.PHONY : src/user.i

# target to preprocess a source file
src/user.cpp.i:
	$(MAKE) -f CMakeFiles/test_user.dir/build.make CMakeFiles/test_user.dir/src/user.cpp.i
	$(MAKE) -f CMakeFiles/test_cloud.dir/build.make CMakeFiles/test_cloud.dir/src/user.cpp.i
	$(MAKE) -f CMakeFiles/test_performance.dir/build.make CMakeFiles/test_performance.dir/src/user.cpp.i
.PHONY : src/user.cpp.i

src/user.s: src/user.cpp.s

.PHONY : src/user.s

# target to generate assembly for a file
src/user.cpp.s:
	$(MAKE) -f CMakeFiles/test_user.dir/build.make CMakeFiles/test_user.dir/src/user.cpp.s
	$(MAKE) -f CMakeFiles/test_cloud.dir/build.make CMakeFiles/test_cloud.dir/src/user.cpp.s
	$(MAKE) -f CMakeFiles/test_performance.dir/build.make CMakeFiles/test_performance.dir/src/user.cpp.s
.PHONY : src/user.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test_miner"
	@echo "... test_user"
	@echo "... test_cloud"
	@echo "... test_performance"
	@echo "... src/cloud.o"
	@echo "... src/cloud.i"
	@echo "... src/cloud.s"
	@echo "... src/miner.o"
	@echo "... src/miner.i"
	@echo "... src/miner.s"
	@echo "... src/test_cloud.o"
	@echo "... src/test_cloud.i"
	@echo "... src/test_cloud.s"
	@echo "... src/test_miner.o"
	@echo "... src/test_miner.i"
	@echo "... src/test_miner.s"
	@echo "... src/test_performance.o"
	@echo "... src/test_performance.i"
	@echo "... src/test_performance.s"
	@echo "... src/test_user.o"
	@echo "... src/test_user.i"
	@echo "... src/test_user.s"
	@echo "... src/user.o"
	@echo "... src/user.i"
	@echo "... src/user.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

